# Change these first
owner: drycc
repo: status
i18n:
  footer: Powered by [Drycc](https://www.drycc.cc)

user-agent: drycc

sites:
  - name: Drycc Community
    url: https://community.drycc.cc
    maxResponseTime: 5000

  - name: Drycc Website
    url: https://www.drycc.cc
    maxResponseTime: 5000

  - name: Drycc Registry
    url: https://registry.drycc.cc/v2/
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 401

  - name: Drycc Woodpecker
    url: https://woodpecker.drycc.cc
    maxResponseTime: 5000

status-website:
  cname: status.drycc.cc
  name: Drycc Status
  theme: light
  introTitle: "Drycc Service Status"
  introMessage: "Real-time monitoring of Drycc public services. Check here for current status, incident history, and uptime metrics."
